[package]
name = "pv_rhino_micdemo"
version = "0.1.1"
edition = "2018"

[dependencies]
chrono = "0.4.23"
clap = "3.2.3"
ctrlc = "3.2.2"
hound = "3.4.0"
itertools = "0.10.3"
pv_recorder = "=1.1.0"
pv_rhino = "=2.1.8"
