name: .NET Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demos.yml'

defaults:
  run:
    working-directory: demo/dotnet/RhinoDemo

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
        - os: windows-latest
          platform: windows
        - os: macos-latest
          platform: mac

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Package restore
      run: dotnet restore

    - name: Dotnet build micdemo
      run: dotnet build -c MicDemo.Release

    - name: Dotnet build filedemo
      run: dotnet build -c FileDemo.Release

    - name: Run Dotnet filedemo
      run: dotnet run -c FileDemo.Release -- --input_audio_path ../../../resources/audio_samples/test_within_context.wav --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --context_path ../../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64]
        include:
        - machine: rpi3-32
          platform: raspberry-pi
        - machine: rpi3-64
          platform: raspberry-pi
        - machine: rpi4-32
          platform: raspberry-pi
        - machine: rpi4-64
          platform: raspberry-pi
        - machine: rpi5-64
          platform: raspberry-pi

    steps:
    - uses: actions/checkout@v3

    - name: Package restore
      run: dotnet restore

    - name: Dotnet build micdemo
      run: dotnet build -c MicDemo.Release

    - name: Dotnet build filedemo
      run: dotnet build -c FileDemo.Release

    - name: Run Dotnet filedemo
      run: dotnet run -c FileDemo.Release -- --input_audio_path ../../../resources/audio_samples/test_within_context.wav --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --context_path ../../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn
