name: Node.js Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'lib/node/**'
      - 'lib/common/**'
      - 'resources/contexts/beaglebone/**'
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/nodejs-perf.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/node/**'
      - 'lib/common/**'
      - 'resources/contexts/beaglebone/**'
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/nodejs-perf.yml'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          performance_threshold_sec: 0.2
        - os: windows-latest
          performance_threshold_sec: 0.2
        - os: macos-latest
          performance_threshold_sec: 0.2

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: yarn test test/perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=100 --performance_threshold_sec=${{matrix.performance_threshold_sec}}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
        - machine: rpi2
          num_test_iterations: 20
          performance_threshold_sec: 2.3
        - machine: rpi3-32
          num_test_iterations: 50
          performance_threshold_sec: 0.6
        - machine: rpi3-64
          num_test_iterations: 50
          performance_threshold_sec: 0.6
        - machine: rpi4-32
          num_test_iterations: 50
          performance_threshold_sec: 0.32
        - machine: rpi4-64
          num_test_iterations: 50
          performance_threshold_sec: 0.32
        - machine: jetson
          num_test_iterations: 50
          performance_threshold_sec: 0.42
        - machine: beaglebone
          num_test_iterations: 20
          performance_threshold_sec: 2.2

    steps:
    - uses: actions/checkout@v2

    - name: Pre-build dependencies
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn install

    - name: Machine state before
      working-directory: resources/scripts
      run: bash machine-state.sh

    - name: Test
      run: yarn test test/perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=${{matrix.num_test_iterations}} --performance_threshold_sec=${{matrix.performance_threshold_sec}}

    - name: Machine state after
      working-directory: resources/scripts
      run: bash machine-state.sh
