name: React Native Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/react-native/**'
      - '!demo/react-native/README.md'
      - '.github/workflows/react-native-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/react-native/**'
      - '!demo/react-native/README.md'
      - '.github/workflows/react-native-demos.yml'

defaults:
  run:
    working-directory: demo/react-native

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

# ************** REMOVE AFTER RELEASE ********************
    - name: Install React Native Binding Dependencies
      run: yarn install
      working-directory: binding/react-native

    - name: Build Local tarball
      run: yarn pkg
      working-directory: binding/react-native

    - name: Remove old package
      run: yarn remove @picovoice/rhino-react-native

    - name: Add new local package
      run: yarn add ../../binding/react-native/pkg/picovoice-rhino-react-native-3.0.4.tgz
# ************** REMOVE AFTER RELEASE ********************

    - name: Install dependencies
      run: yarn android-install

    - name: Build bundle
      run: yarn android-bundle ko

    - name: Build
      run: ./gradlew assembleDebug
      working-directory: demo/react-native/android

  build-ios:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

# ************** REMOVE AFTER RELEASE ********************
    - name: Install React Native Binding Dependencies
      run: yarn install
      working-directory: binding/react-native

    - name: Build Local tarball
      run: yarn pkg
      working-directory: binding/react-native

    - name: Remove old package
      run: yarn remove @picovoice/rhino-react-native

    - name: Add new local package
      run: yarn add ../../binding/react-native/pkg/picovoice-rhino-react-native-3.0.4.tgz
# ************** REMOVE AFTER RELEASE ********************

    - name: Install dependencies
      run: yarn ios-install

    - name: Build bundle
      run: yarn ios-bundle ja

    - name: Build
      run: xcrun xcodebuild build
        -configuration Debug
        -workspace RhinoDemo.xcworkspace
        -sdk iphoneos
        -scheme RhinoDemo
        -derivedDataPath ddp
        CODE_SIGNING_ALLOWED=NO
      working-directory: demo/react-native/ios
